# Generated by Django 4.2.5 on 2023-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BandPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_price', models.FloatField(default=0)),
                ('under_30s_price', models.FloatField(default=0)),
                ('sibling_price', models.FloatField(default=0)),
                ('bands', models.ManyToManyField(blank=True, to='polls.band')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='polls.instrument'),
        ),
    ]
