# Generated by Django 4.2.5 on 2023-09-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bandpackage',
            name='full_price',
        ),
        migrations.RemoveField(
            model_name='bandpackage',
            name='under_30s_price',
        ),
        migrations.CreateModel(
            name='TermPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.FloatField(default=0)),
                ('under_30s_price', models.FloatField(default=0)),
                ('band_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bandpackage')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.term')),
            ],
        ),
    ]
