# Generated by Django 4.2.5 on 2023-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_term_remove_bandpackage_full_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandpackage',
            name='sibling_price',
        ),
        migrations.AddField(
            model_name='termprice',
            name='sibling_price',
            field=models.FloatField(default=0),
        ),
    ]
