# Generated by Django 4.2.5 on 2023-10-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_bandpackage_sibling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.productcategory')),
                ('products', models.ManyToManyField(blank=True, to='polls.product')),
            ],
        ),
        migrations.CreateModel(
            name='TermProductPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.FloatField(default=0)),
                ('under_30s_price', models.FloatField(default=0)),
                ('sibling_price', models.FloatField(default=0)),
                ('product_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.productpackage')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.term')),
            ],
        ),
        migrations.RemoveField(
            model_name='bandpackage',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='termprice',
            name='band_package',
        ),
        migrations.RemoveField(
            model_name='termprice',
            name='term',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='BandPackage',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='TermPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.productcategory'),
        ),
    ]
