name: Master Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - domi/**
      - Pipfile*
      - zappa_settings.json

env:
  AWS_REGION:
    "eu-west-2" #Change to reflect your Region


    # Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::984617344736:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Setup Profile
        run: |
          aws configure set region ${{ env.AWS_REGION }} --profile django
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile django
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile django
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile django

      - name: Show profile
        run: |
          cat ~/.aws/config

      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pipenv, libpq, and pandoc
        run: |
          sudo apt-get install libpq-dev -y
          pip install pipenv

      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install

      - name: Move sqllite binary in place
        run: mv bla/* .
      - name: Zappa deployments
        run: pipenv run zappa update --all
